import Descriptions from "@/components/Descriptions";
import Parent from "@/components/Parent";
import User from "@/components/User";
import Welcome from "@/components/Welcome";
import Dog from "@/components/Dog";
import Head from "next/head";
import Counter from "@/components/Counter";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Olá Mundo</h1>
        {/*Comentário em JSX */}
        <Welcome/>
        <User/>
        <Parent/>
        {/* Chamando o componente e passando as props */}
        <Descriptions name="Pedro" age={23}/>
        {/* Usando a desestruturação para passar props */}
        <Dog name="Rex" breed="Pitbull"/>
        <Counter/>
      </main>
    </>
  );
}
